INSERT INTO checkout_country (name) VALUES (E'Afghanistan');
INSERT INTO checkout_country (name) VALUES (E'Åland Islands');
INSERT INTO checkout_country (name) VALUES (E'Albania');
INSERT INTO checkout_country (name) VALUES (E'Algeria');
INSERT INTO checkout_country (name) VALUES (E'American Samoa');
INSERT INTO checkout_country (name) VALUES (E'Andorra');
INSERT INTO checkout_country (name) VALUES (E'Angola');
INSERT INTO checkout_country (name) VALUES (E'Anguilla');
INSERT INTO checkout_country (name) VALUES (E'Antarctica');
INSERT INTO checkout_country (name) VALUES (E'Antigua & Barbuda');
INSERT INTO checkout_country (name) VALUES (E'Argentina');
INSERT INTO checkout_country (name) VALUES (E'Armenia');
INSERT INTO checkout_country (name) VALUES (E'Aruba');
INSERT INTO checkout_country (name) VALUES (E'Australia');
INSERT INTO checkout_country (name) VALUES (E'Austria');
INSERT INTO checkout_country (name) VALUES (E'Azerbaijan');
INSERT INTO checkout_country (name) VALUES (E'Bahamas');
INSERT INTO checkout_country (name) VALUES (E'Bahrain');
INSERT INTO checkout_country (name) VALUES (E'Bangladesh');
INSERT INTO checkout_country (name) VALUES (E'Barbados');
INSERT INTO checkout_country (name) VALUES (E'Belarus');
INSERT INTO checkout_country (name) VALUES (E'Belgium');
INSERT INTO checkout_country (name) VALUES (E'Belize');
INSERT INTO checkout_country (name) VALUES (E'Benin');
INSERT INTO checkout_country (name) VALUES (E'Bermuda');
INSERT INTO checkout_country (name) VALUES (E'Bhutan');
INSERT INTO checkout_country (name) VALUES (E'Bolivia');
INSERT INTO checkout_country (name) VALUES (E'Bosnia & Herzegovina');
INSERT INTO checkout_country (name) VALUES (E'Botswana');
INSERT INTO checkout_country (name) VALUES (E'Bouvet Island');
INSERT INTO checkout_country (name) VALUES (E'Brazil');
INSERT INTO checkout_country (name) VALUES (E'British Indian Ocean Territory');
INSERT INTO checkout_country (name) VALUES (E'British Virgin Islands');
INSERT INTO checkout_country (name) VALUES (E'Brunei');
INSERT INTO checkout_country (name) VALUES (E'Bulgaria');
INSERT INTO checkout_country (name) VALUES (E'Burkina Faso');
INSERT INTO checkout_country (name) VALUES (E'Burundi');
INSERT INTO checkout_country (name) VALUES (E'Cambodia');
INSERT INTO checkout_country (name) VALUES (E'Cameroon');
INSERT INTO checkout_country (name) VALUES (E'Canada');
INSERT INTO checkout_country (name) VALUES (E'Cape Verde');
INSERT INTO checkout_country (name) VALUES (E'Caribbean Netherlands');
INSERT INTO checkout_country (name) VALUES (E'Cayman Islands');
INSERT INTO checkout_country (name) VALUES (E'Central African Republic');
INSERT INTO checkout_country (name) VALUES (E'Chad');
INSERT INTO checkout_country (name) VALUES (E'Chile');
INSERT INTO checkout_country (name) VALUES (E'China');
INSERT INTO checkout_country (name) VALUES (E'Christmas Island');
INSERT INTO checkout_country (name) VALUES (E'Cocos (Keeling) Islands');
INSERT INTO checkout_country (name) VALUES (E'Colombia');
INSERT INTO checkout_country (name) VALUES (E'Comoros');
INSERT INTO checkout_country (name) VALUES (E'Congo - Brazzaville');
INSERT INTO checkout_country (name) VALUES (E'Congo - Kinshasa');
INSERT INTO checkout_country (name) VALUES (E'Cook Islands');
INSERT INTO checkout_country (name) VALUES (E'Costa Rica');
INSERT INTO checkout_country (name) VALUES (E'Côte d’Ivoire');
INSERT INTO checkout_country (name) VALUES (E'Croatia');
INSERT INTO checkout_country (name) VALUES (E'Cuba');
INSERT INTO checkout_country (name) VALUES (E'Curaçao');
INSERT INTO checkout_country (name) VALUES (E'Cyprus');
INSERT INTO checkout_country (name) VALUES (E'Czechia');
INSERT INTO checkout_country (name) VALUES (E'Denmark');
INSERT INTO checkout_country (name) VALUES (E'Djibouti');
INSERT INTO checkout_country (name) VALUES (E'Dominica');
INSERT INTO checkout_country (name) VALUES (E'Dominican Republic');
INSERT INTO checkout_country (name) VALUES (E'Ecuador');
INSERT INTO checkout_country (name) VALUES (E'Egypt');
INSERT INTO checkout_country (name) VALUES (E'El Salvador');
INSERT INTO checkout_country (name) VALUES (E'Equatorial Guinea');
INSERT INTO checkout_country (name) VALUES (E'Eritrea');
INSERT INTO checkout_country (name) VALUES (E'Estonia');
INSERT INTO checkout_country (name) VALUES (E'Eswatini');
INSERT INTO checkout_country (name) VALUES (E'Ethiopia');
INSERT INTO checkout_country (name) VALUES (E'Falkland Islands');
INSERT INTO checkout_country (name) VALUES (E'Faroe Islands');
INSERT INTO checkout_country (name) VALUES (E'Fiji');
INSERT INTO checkout_country (name) VALUES (E'Finland');
INSERT INTO checkout_country (name) VALUES (E'France');
INSERT INTO checkout_country (name) VALUES (E'French Guiana');
INSERT INTO checkout_country (name) VALUES (E'French Polynesia');
INSERT INTO checkout_country (name) VALUES (E'French Southern Territories');
INSERT INTO checkout_country (name) VALUES (E'Gabon');
INSERT INTO checkout_country (name) VALUES (E'Gambia');
INSERT INTO checkout_country (name) VALUES (E'Georgia');
INSERT INTO checkout_country (name) VALUES (E'Germany');
INSERT INTO checkout_country (name) VALUES (E'Ghana');
INSERT INTO checkout_country (name) VALUES (E'Gibraltar');
INSERT INTO checkout_country (name) VALUES (E'Greece');
INSERT INTO checkout_country (name) VALUES (E'Greenland');
INSERT INTO checkout_country (name) VALUES (E'Grenada');
INSERT INTO checkout_country (name) VALUES (E'Guadeloupe');
INSERT INTO checkout_country (name) VALUES (E'Guam');
INSERT INTO checkout_country (name) VALUES (E'Guatemala');
INSERT INTO checkout_country (name) VALUES (E'Guernsey');
INSERT INTO checkout_country (name) VALUES (E'Guinea');
INSERT INTO checkout_country (name) VALUES (E'Guinea-Bissau');
INSERT INTO checkout_country (name) VALUES (E'Guyana');
INSERT INTO checkout_country (name) VALUES (E'Haiti');
INSERT INTO checkout_country (name) VALUES (E'Heard & McDonald Islands');
INSERT INTO checkout_country (name) VALUES (E'Honduras');
INSERT INTO checkout_country (name) VALUES (E'Hong Kong SAR China');
INSERT INTO checkout_country (name) VALUES (E'Hungary');
INSERT INTO checkout_country (name) VALUES (E'Iceland');
INSERT INTO checkout_country (name) VALUES (E'India');
INSERT INTO checkout_country (name) VALUES (E'Indonesia');
INSERT INTO checkout_country (name) VALUES (E'Iran');
INSERT INTO checkout_country (name) VALUES (E'Iraq');
INSERT INTO checkout_country (name) VALUES (E'Ireland');
INSERT INTO checkout_country (name) VALUES (E'Isle of Man');
INSERT INTO checkout_country (name) VALUES (E'Israel');
INSERT INTO checkout_country (name) VALUES (E'Italy');
INSERT INTO checkout_country (name) VALUES (E'Jamaica');
INSERT INTO checkout_country (name) VALUES (E'Japan');
INSERT INTO checkout_country (name) VALUES (E'Jersey');
INSERT INTO checkout_country (name) VALUES (E'Jordan');
INSERT INTO checkout_country (name) VALUES (E'Kazakhstan');
INSERT INTO checkout_country (name) VALUES (E'Kenya');
INSERT INTO checkout_country (name) VALUES (E'Kiribati');
INSERT INTO checkout_country (name) VALUES (E'Kuwait');
INSERT INTO checkout_country (name) VALUES (E'Kyrgyzstan');
INSERT INTO checkout_country (name) VALUES (E'Laos');
INSERT INTO checkout_country (name) VALUES (E'Latvia');
INSERT INTO checkout_country (name) VALUES (E'Lebanon');
INSERT INTO checkout_country (name) VALUES (E'Lesotho');
INSERT INTO checkout_country (name) VALUES (E'Liberia');
INSERT INTO checkout_country (name) VALUES (E'Libya');
INSERT INTO checkout_country (name) VALUES (E'Liechtenstein');
INSERT INTO checkout_country (name) VALUES (E'Lithuania');
INSERT INTO checkout_country (name) VALUES (E'Luxembourg');
INSERT INTO checkout_country (name) VALUES (E'Macao SAR China');
INSERT INTO checkout_country (name) VALUES (E'Madagascar');
INSERT INTO checkout_country (name) VALUES (E'Malawi');
INSERT INTO checkout_country (name) VALUES (E'Malaysia');
INSERT INTO checkout_country (name) VALUES (E'Maldives');
INSERT INTO checkout_country (name) VALUES (E'Mali');
INSERT INTO checkout_country (name) VALUES (E'Malta');
INSERT INTO checkout_country (name) VALUES (E'Marshall Islands');
INSERT INTO checkout_country (name) VALUES (E'Martinique');
INSERT INTO checkout_country (name) VALUES (E'Mauritania');
INSERT INTO checkout_country (name) VALUES (E'Mauritius');
INSERT INTO checkout_country (name) VALUES (E'Mayotte');
INSERT INTO checkout_country (name) VALUES (E'Mexico');
INSERT INTO checkout_country (name) VALUES (E'Micronesia');
INSERT INTO checkout_country (name) VALUES (E'Moldova');
INSERT INTO checkout_country (name) VALUES (E'Monaco');
INSERT INTO checkout_country (name) VALUES (E'Mongolia');
INSERT INTO checkout_country (name) VALUES (E'Montenegro');
INSERT INTO checkout_country (name) VALUES (E'Montserrat');
INSERT INTO checkout_country (name) VALUES (E'Morocco');
INSERT INTO checkout_country (name) VALUES (E'Mozambique');
INSERT INTO checkout_country (name) VALUES (E'Myanmar (Burma)');
INSERT INTO checkout_country (name) VALUES (E'Namibia');
INSERT INTO checkout_country (name) VALUES (E'Nauru');
INSERT INTO checkout_country (name) VALUES (E'Nepal');
INSERT INTO checkout_country (name) VALUES (E'Netherlands');
INSERT INTO checkout_country (name) VALUES (E'New Caledonia');
INSERT INTO checkout_country (name) VALUES (E'New Zealand');
INSERT INTO checkout_country (name) VALUES (E'Nicaragua');
INSERT INTO checkout_country (name) VALUES (E'Niger');
INSERT INTO checkout_country (name) VALUES (E'Nigeria');
INSERT INTO checkout_country (name) VALUES (E'Niue');
INSERT INTO checkout_country (name) VALUES (E'Norfolk Island');
INSERT INTO checkout_country (name) VALUES (E'North Korea');
INSERT INTO checkout_country (name) VALUES (E'North Macedonia');
INSERT INTO checkout_country (name) VALUES (E'Northern Mariana Islands');
INSERT INTO checkout_country (name) VALUES (E'Norway');
INSERT INTO checkout_country (name) VALUES (E'Oman');
INSERT INTO checkout_country (name) VALUES (E'Pakistan');
INSERT INTO checkout_country (name) VALUES (E'Palau');
INSERT INTO checkout_country (name) VALUES (E'Palestinian Territories');
INSERT INTO checkout_country (name) VALUES (E'Panama');
INSERT INTO checkout_country (name) VALUES (E'Papua New Guinea');
INSERT INTO checkout_country (name) VALUES (E'Paraguay');
INSERT INTO checkout_country (name) VALUES (E'Peru');
INSERT INTO checkout_country (name) VALUES (E'Philippines');
INSERT INTO checkout_country (name) VALUES (E'Pitcairn Islands');
INSERT INTO checkout_country (name) VALUES (E'Poland');
INSERT INTO checkout_country (name) VALUES (E'Portugal');
INSERT INTO checkout_country (name) VALUES (E'Puerto Rico');
INSERT INTO checkout_country (name) VALUES (E'Qatar');
INSERT INTO checkout_country (name) VALUES (E'Réunion');
INSERT INTO checkout_country (name) VALUES (E'Romania');
INSERT INTO checkout_country (name) VALUES (E'Russia');
INSERT INTO checkout_country (name) VALUES (E'Rwanda');
INSERT INTO checkout_country (name) VALUES (E'Samoa');
INSERT INTO checkout_country (name) VALUES (E'San Marino');
INSERT INTO checkout_country (name) VALUES (E'São Tomé & Príncipe');
INSERT INTO checkout_country (name) VALUES (E'Saudi Arabia');
INSERT INTO checkout_country (name) VALUES (E'Senegal');
INSERT INTO checkout_country (name) VALUES (E'Serbia');
INSERT INTO checkout_country (name) VALUES (E'Seychelles');
INSERT INTO checkout_country (name) VALUES (E'Sierra Leone');
INSERT INTO checkout_country (name) VALUES (E'Singapore');
INSERT INTO checkout_country (name) VALUES (E'Sint Maarten');
INSERT INTO checkout_country (name) VALUES (E'Slovakia');
INSERT INTO checkout_country (name) VALUES (E'Slovenia');
INSERT INTO checkout_country (name) VALUES (E'Solomon Islands');
INSERT INTO checkout_country (name) VALUES (E'Somalia');
INSERT INTO checkout_country (name) VALUES (E'South Africa');
INSERT INTO checkout_country (name) VALUES (E'South Georgia & South Sandwich Islands');
INSERT INTO checkout_country (name) VALUES (E'South Korea');
INSERT INTO checkout_country (name) VALUES (E'South Sudan');
INSERT INTO checkout_country (name) VALUES (E'Spain');
INSERT INTO checkout_country (name) VALUES (E'Sri Lanka');
INSERT INTO checkout_country (name) VALUES (E'St. Barthélemy');
INSERT INTO checkout_country (name) VALUES (E'St. Helena');
INSERT INTO checkout_country (name) VALUES (E'St. Kitts & Nevis');
INSERT INTO checkout_country (name) VALUES (E'St. Lucia');
INSERT INTO checkout_country (name) VALUES (E'St. Martin');
INSERT INTO checkout_country (name) VALUES (E'St. Pierre & Miquelon');
INSERT INTO checkout_country (name) VALUES (E'St. Vincent & Grenadines');
INSERT INTO checkout_country (name) VALUES (E'Sudan');
INSERT INTO checkout_country (name) VALUES (E'Suriname');
INSERT INTO checkout_country (name) VALUES (E'Svalbard & Jan Mayen');
INSERT INTO checkout_country (name) VALUES (E'Sweden');
INSERT INTO checkout_country (name) VALUES (E'Switzerland');
INSERT INTO checkout_country (name) VALUES (E'Syria');
INSERT INTO checkout_country (name) VALUES (E'Taiwan');
INSERT INTO checkout_country (name) VALUES (E'Tajikistan');
INSERT INTO checkout_country (name) VALUES (E'Tanzania');
INSERT INTO checkout_country (name) VALUES (E'Thailand');
INSERT INTO checkout_country (name) VALUES (E'Timor-Leste');
INSERT INTO checkout_country (name) VALUES (E'Togo');
INSERT INTO checkout_country (name) VALUES (E'Tokelau');
INSERT INTO checkout_country (name) VALUES (E'Tonga');
INSERT INTO checkout_country (name) VALUES (E'Trinidad & Tobago');
INSERT INTO checkout_country (name) VALUES (E'Tunisia');
INSERT INTO checkout_country (name) VALUES (E'Turkey');
INSERT INTO checkout_country (name) VALUES (E'Turkmenistan');
INSERT INTO checkout_country (name) VALUES (E'Turks & Caicos Islands');
INSERT INTO checkout_country (name) VALUES (E'Tuvalu');
INSERT INTO checkout_country (name) VALUES (E'U.S. Outlying Islands');
INSERT INTO checkout_country (name) VALUES (E'U.S. Virgin Islands');
INSERT INTO checkout_country (name) VALUES (E'Uganda');
INSERT INTO checkout_country (name) VALUES (E'Ukraine');
INSERT INTO checkout_country (name) VALUES (E'United Arab Emirates');
INSERT INTO checkout_country (name) VALUES (E'United Kingdom');
INSERT INTO checkout_country (name) VALUES (E'United States');
INSERT INTO checkout_country (name) VALUES (E'Uruguay');
INSERT INTO checkout_country (name) VALUES (E'Uzbekistan');
INSERT INTO checkout_country (name) VALUES (E'Vanuatu');
INSERT INTO checkout_country (name) VALUES (E'Vatican City');
INSERT INTO checkout_country (name) VALUES (E'Venezuela');
INSERT INTO checkout_country (name) VALUES (E'Vietnam');
INSERT INTO checkout_country (name) VALUES (E'Wallis & Futuna');
INSERT INTO checkout_country (name) VALUES (E'Western Sahara');
INSERT INTO checkout_country (name) VALUES (E'Yemen');
INSERT INTO checkout_country (name) VALUES (E'Zambia');
INSERT INTO checkout_country (name) VALUES (E'Zimbabwe');name