# Generated by Django 4.0.4 on 2022-05-09 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_rename_posting_id_bids_posting_and_more'),
        ('catalogue', '0003_rename_posting_id_bids_posting_and_more'),
    ]

    operations = [
    ]
