# Generated by Django 4.0.4 on 2022-05-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_remove_items_item_picture_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='image1',
            field=models.CharField(default='https://cdn.mos.cms.futurecdn.net/Z7STxMEovJyL8GF45PviiR.jpg', max_length=9999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='items',
            name='image2',
            field=models.CharField(blank=True, max_length=9999),
        ),
        migrations.AddField(
            model_name='items',
            name='image3',
            field=models.CharField(blank=True, max_length=9999),
        ),
        migrations.AddField(
            model_name='items',
            name='image4',
            field=models.CharField(blank=True, max_length=9999),
        ),
        migrations.AddField(
            model_name='items',
            name='image5',
            field=models.CharField(blank=True, max_length=9999),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
