# Generated by Django 4.0.4 on 2022-05-09 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='posting_id',
            new_name='posting',
        ),
        migrations.RenameField(
            model_name='postings',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='ratings',
            old_name='posting_id',
            new_name='posting',
        ),
        migrations.RemoveField(
            model_name='bids',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='ratings',
            name='user_id',
        ),
        migrations.AddField(
            model_name='bids',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postings',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ratings',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
