# Generated by Django 4.0.4 on 2022-05-09 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_alter_bids_user_id_alter_ratings_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='posting_id',
            new_name='posting',
        ),
        migrations.RenameField(
            model_name='bids',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='postings',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='ratings',
            old_name='posting_id',
            new_name='posting',
        ),
        migrations.RenameField(
            model_name='ratings',
            old_name='user_id',
            new_name='user',
        ),
    ]
