# Generated by Django 4.0.4 on 2022-05-11 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('street_name', models.CharField(max_length=100)),
                ('street_no', models.IntegerField()),
                ('post_code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('card_no', models.IntegerField(max_length=16)),
                ('expiration_date', models.DateField()),
                ('cvc', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.contacts')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.payments')),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.postings')),
            ],
        ),
        migrations.AddField(
            model_name='contacts',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.country'),
        ),
    ]
