# Generated by Django 4.0.4 on 2022-05-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_alter_payments_card_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='street_no',
            new_name='house_no',
        ),
        migrations.AddField(
            model_name='contacts',
            name='city',
            field=models.CharField(default='home', max_length=100),
            preserve_default=False,
        ),
    ]
